import { SmartLinkAccess, SmartLinkType } from '@/types';


export const smartLinkAccessOptions = [
	{ label: 'Public', value: SmartLinkAccess.PUBLIC },
	{ label: 'Public with data collection', value: SmartLinkAccess.SHARED },
	{ label: 'Private email list', value: SmartLinkAccess.PRIVATE },
	{ label: 'Paywalled content', value: SmartLinkAccess.PAYWALL }
];

export const smartLinkTypeOfAccessOptions = [
	{ label: 'View only', value: SmartLinkType.VIEW },
	{ label: 'View and download', value: SmartLinkType.VIEW_AND_DOWNLOAD }
];

export const CONTINENTS = [
  { code: "NA", label: "North America", countries: ["US", "CA", "MX"] },
  { code: "UK", label: "UK & Ireland", countries: ["GB", "IE"] },
  {
    code: "WE",
    label: "Western Europe",
    countries: [
      "FR",
      "DE",
      "AT",
      "BE",
      "CH",
      "LI",
      "LU",
      "MC",
      "NL",
      "AD",
      "SM",
    ],
  },
  {
    code: "SN",
    label: "Scandinavia & Nordic",
    countries: ["DK", "FI", "IS", "NO", "SE"],
  },
  {
    code: "EE",
    label: "Eastern Europe",
    countries: [
      "BG",
      "BY",
      "CZ",
      "EE",
      "HU",
      "LT",
      "LV",
      "MD",
      "PL",
      "RO",
      "RU",
      "SK",
      "UA",
      "AL",
      "BA",
      "HR",
      "ME",
    ],
  },
  {
    code: "MENA",
    label: "MENA (Middle East & North Africa)",
    countries: [
      "DZ",
      "EG",
      "IR",
      "IQ",
      "IL",
      "JO",
      "KW",
      "LB",
      "LY",
      "MA",
      "OM",
      "PS",
      "QA",
      "SA",
      "SY",
      "TN",
      "TR",
      "AE",
      "YE",
    ],
  },
  {
    code: "SSA",
    label: "Sub-Saharan Africa",
    countries: [
      "AO",
      "BJ",
      "BW",
      "BF",
      "BI",
      "CM",
      "CV",
      "CF",
      "TD",
      "KM",
      "CG",
      "CD",
      "DJ",
      "GQ",
      "ER",
      "SZ",
      "ET",
      "GA",
      "GM",
      "GH",
      "GN",
      "GW",
      "CI",
      "KE",
      "LS",
      "LR",
      "MG",
      "MW",
      "ML",
      "MR",
      "MU",
      "YT",
      "MZ",
      "NA",
      "NE",
      "NG",
      "RE",
      "RW",
      "ST",
      "SN",
      "SC",
      "SL",
      "SO",
      "ZA",
      "SS",
      "SD",
      "TZ",
      "TG",
      "TG",
      "UG",
      "ZM",
      "ZW",
    ],
  },
  {
    code: "AS",
    label: "Asia Pacific",
    countries: [
      "AU",
      "NZ",
      "FJ",
      "PG",
      "SB",
      "VU",
      "NC",
      "PF",
      "WS",
      "TO",
      "TV",
      "KI",
      "NR",
      "MH",
      "FM",
      "PW",
    ],
  },
  {
    code: "SA",
    label: "South Asia",
    countries: ["AF", "BD", "BT", "IN", "MV", "NP", "PK", "LK"],
  },
  {
    code: "LA",
    label: "Latin America",
    countries: [
      "AR",
      "BO",
      "BR",
      "CL",
      "CO",
      "EC",
      "GF",
      "GY",
      "PY",
      "PE",
      "SR",
      "UY",
      "VE",
    ],
  },
  {
    code: "CA",
    label: "Caribbean & Central America",
    countries: [
      "AG",
      "BS",
      "BB",
      "BZ",
      "CR",
      "CU",
      "DM",
      "DO",
      "SV",
      "GD",
      "GT",
      "HT",
      "HN",
      "JM",
      "KN",
      "LC",
      "MS",
      "NI",
      "PA",
      "PR",
      "BL",
      "VC",
      "SX",
      "TT",
      "TC",
      "VG",
      "VI",
    ],
  },
  {
    code: "RU",
    label: "Russia & CIS",
    countries: [
      "RU",
      "AM",
      "AZ",
      "BY",
      "GE",
      "KZ",
      "KG",
      "MD",
      "TJ",
      "TM",
      "UA",
      "UZ",
    ],
  },
  {
    code: "CN",
    label: "China & Greater China",
    countries: ["CN", "HK", "MO", "TW"],
  },
];
